language: elixir
sudo: false
elixir:
  - 1.6.4
otp_release:
  - 20.3

addons:
  postgresql: "9.6"

env:
  - MIX_ENV=test

before_script:
  - mix deps.compile
  - mix compile --warnings-as-errors

script:
  - mix format --check-formatted
  - mix safe_coveralls.travis

cache:
  directories:
    - _build
    - deps
